### Group to analyze ###
group: ""

### Environment.yaml for Qiime2 activation ###
CONDAENV: "/BiO/Access/home/user1/dnalink/quest/envs/qiime2-amplicon-2024.5-py39-linux-conda.yml"

### Rawdata import options ###
sample_type: "'SampleData[PairedEndSequencesWithQuality]'"
input_format: "PairedEndFastqManifestPhred33V2"

### Primer trimming & Quality filtereing ###
primer_fwd: "CCTACGGGNGGCWGCAG"
primer_rev: "GACTACHVGGGTATCTAATCC"
q_score: 20

### Clustering ###
threads: 80
seq_identity: 0.97

### Taxonomic analysis ###
classifier: "/BiO/Install/Metagenome/RefDB/ncbi-refseqs-classifier.qza"
